baseURL = "https://okuda0715tech.github.io/"
languageCode = "ja"
title = "奥田智紘の技術ブログ"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "auto"
showReadingTime = true
showShareButtons = true
