# 独自 URL に変更する場合は baseURL を変更するだけで OK
baseURL = "https://design.okuda-studio.com/"

languageCode = "ja"
title = "設計で、迷わなくなるために | 奥田智紘"
theme = "PaperMod"

[pagination]
pagerSize = 100

[menu]

  [[menu.main]]
    name = "記事"
    url = "/posts/"
    weight = 1
    
  [[menu.main]]
    name = "本"
    url = "/books/"
    weight = 2
    
  [[menu.main]]
    name = "概要"
    url = "/about/"
    weight = 10

[params]
defaultTheme = "auto"
showReadingTime = true
showShareButtons = true
env = "production"

  [params.profileMode]
    enabled = true
    title = "設計で、迷わなくなるために。"
    subtitle = "判断・責務・境界を言語化する技術と思考のログ"
#    imageUrl = "/images/profile.png" # 今は無くてもOK
#    imageTitle = "okuda0715"

[services.googleAnalytics]
id = "G-W5RMQW8ZBN"

